services:
  postgresql:
    container_name: postgres_sosu
    image: postgres
    environment:
      POSTGRES_USER: sosu
      POSTGRES_PASSWORD: mypassword
      PGDATA: /data/postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - sosu_network

  mongodb:
    container_name: mongo_sosu
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: sosu
      MONGO_INITDB_ROOT_PASSWORD: mypassword
    volumes:
      - mongo:/data/db
      - mongo_config:/data/configdb
    ports:
      - "27017:27017"
    networks:
      - sosu_network

  mongo-express:
    container_name: sosu_mongo_express
    image: mongo-express:latest
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: sosu
      ME_CONFIG_MONGODB_ADMINPASSWORD: mypassword
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: sosu
      ME_CONFIG_BASICAUTH_PASSWORD: mypassword
    ports:
      - "8081:8081"
    networks:
      - sosu_network

  zookeeper:   #server virtuale sul quale runna kafka
    image: confluentinc/cp-zookeeper:latest
    container_name: sosu_zookeeper
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    networks:
      - sosu_network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: sosu_kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_OFFSET_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT, PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    networks:
      - sosu_network

  mail-dev:
    container_name: sosu_maildev
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
    networks:
      - sosu_network




networks:
  sosu_network:
    driver: bridge

volumes:
  postgres:
  mongo:
  mongo_config:
